### ISSUE TITLE
[video recording] some quality of life improvements

### ISSUE THREAD

**Issue by aytunch** [Apparence-io/CamerAwesome#143]
## Proposal
**1-**
ability to pause and resume a video recording. Most modern apps allow users to pause a video recording and continue recording after some delay. And once the recording is stopped, we get the combined video with all the intervals present.

some things to keep in mind which can be tricky are;
What if user changes camera(front/back) while in paused state? should it be allowed?
What if phone orientation changes?

Can native camera packages support this or does this need to be done manually by stitching videos together?

**2-**
A way to get the current recorded time in milliseconds during recording and when recording is finished.
This will be useful when we are showing a progress indicator with a max recording duration

Unfortunately, the official camera plugin can not accomplish these features.

**Comment by apalala-dev** [comment]
First point should be working on master now. Pause and resume buttons are now working with the `awesome` builder.

Second point seems to be a Widget that stops recording after a specific duration, with a progress indicating how much time has passed since the recording started.
I believe that a pure Widget implementation should be enough for this, or am I missing something ?
