### ISSUE TITLE
[Question]About front camera mirroring in video recording 

### ISSUE THREAD

**Issue by dar814** [Apparence-io/CamerAwesome#331]
Does ''enable/disable front camera mirroring'' only work on taking a picture? The result mp4 file of video recording is still mirrored compared with the camera preview when using the front camera.

**Comment by apalala-dev** [comment]
Please, specify on which platform you are trying to use the feature. Since Android and iOS are handled differently, behaviours may be different.

About this specific issue on **Android**: yes, `mirrorFrontCamera` only supports taking pictures for now. The Android video equivalent native API just [released a few days ago](https://developer.android.com/jetpack/androidx/releases/camera#version_13_2), so we might include it in a later release (same parameter but it will also apply to videos).

I believe that the **iOS** part doesn't mirror videos as well from a quick check in the code, but I may have missed it.
@istornz can you confirm it is not implemented yet?

**Comment by apalala-dev** [comment]
We pre-released the 2.0.0 version that you can can find [here](https://pub.dev/packages/camerawesome/versions/2.0.0-dev.1).
Among the new features, it also includes the ability to mirror video recordings.
I'll close the issue as it's now implemented on both Android & iOS platforms.
