### ISSUE TITLE
Landscape

### ISSUE THREAD

**Issue by lthoedt** [Apparence-io/CamerAwesome#419]
## Proposal

I want to use this in landscape mode but it seems to be locked to portrait mode. Im working on a work around but im not sure that that is possible yet.
Is there a reason for it not being supported?

**Comment by g-apparence** [comment]
Hi, 
CamerAwesome locks orientation to portrait mode as the sensor orientation on phones. 
There is another issue requesting to change the orientation on tablets. 
Is that what you want to achieve?

**Comment by lthoedt** [comment]
I want to rotate the phone to landscape and make the interface in portrait. However after overwriting the orientation, the camera view also rotates and now is rotated wrong.

**Comment by g-apparence** [comment]
Yes, that's why we locked the rotation. 

If you want to create a landscape view you will have to draw your custom view and use the AwesomeRotateWidget to rotate your widgets. 
Basically, you have to make the same render as we made but instead of wrapping the elements within a Column you have to push them as a Row.

**Comment by lthoedt** [comment]
Right, that is what i did but its rather awkward. I cant seem to understand why the default camera package works but camerawesome behaves different.

**Comment by Mohammad-R-Rashid** [comment]
Yeah with the camera package, its easy to keep it locked in landscape.
